version: '3'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6380:6379"
    networks:
      - redis-replication

  redis-slave:
    image: redis:latest
    container_name: redis-slave
    ports:
      - "6381:6379"
    links:
        - redis-master
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master
    networks:
      - redis-replication

networks:
  redis-replication:
    driver: bridge